### PR TITLE
Update to version 0.19.0

### PR DESCRIPTION
**Pull request by jdblischak**
I am interested in helping maintain [git2r](https://cran.r-project.org/package=git2r) so I also added myself to the maintainer list.

### CODE REVIEW

**Comment by jdblischak** [comment]
Please review @johanneskoester and @bgruening

**Comment by bgruening** [comment]
+1 looks good. I can not merge from my mobile... will do asap.

**Comment by bgruening** [comment]
Sorry for talking so long ...

**Comment by jdblischak** [comment]
Thanks, @bgruening! That was super fast!

**Pull request merged**
